### ISSUE TITLE
Use structopt to define CLI commands

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [arusahni/git-req#47]
[structopt](https://github.com/TeXitoi/structopt) is a create that wraps `clap` functionalities with some custom derive macros so the command line options can be specified with some Rust struct definitions and macro parameters.

I personally find `structopt` code's more clear to read and easier to maintain than using `clap` directly. I use `structopt` in most of my cli apps, I wouldn't mind porting from `clap` to `structopt`. Just want to know if it would be desirable before I put in the time for it.

**Comment by arusahni** [comment]
Hi - thanks for the suggestion! I've been eying structopt because it seems like what the community's rallying behind. I wouldn't be averse to a change, but I do have a (possibly dumb) question - would this break the yaml-based method by which git-req generates its manpage (assuming no duplication of declarations)?

**Comment by Jonathas-Conceicao** [comment]
I hadn't noticed before that the yml config file was also used to generate an man page. structopt, will generate `--help` commands but as far as I know, it doesn't generate an manpage.

**Comment by arusahni** [comment]
It seems as if Git intercepts `--help` and serves the manpage for the extension instead of passing it through.

**Comment by Jonathas-Conceicao** [comment]
Looks like it. However the `-h` does works for me.

**Comment by arusahni** [comment]
Closing as this is not something I'd pursue given the desire for manpage support.
